// app/layout.tsx
import type { Metadata } from "next";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/custom/Navbar";
import { UserProvider } from "@/providers/UserProvider";

import "./globals.css";

import { Open_Sans } from "next/font/google";

const openSans = Open_Sans({
	subsets: ["latin"],
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const CLIENT_ID = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID;
if (!CLIENT_ID) throw new Error("Google Client ID is not defined");

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<GoogleOAuthProvider clientId={CLIENT_ID!}>
			<html lang="en" className={openSans.className}>
				<body className="h-screen flex flex-col overflow-hidden">
					<Navbar />
					<UserProvider>
						<div className="flex flex-1 overflow-hidden">
							{/* Main scrollable area */}
							<main className="flex-1 p-4">{children}</main>
						</div>
					</UserProvider>
					<Toaster richColors />
				</body>
			</html>
		</GoogleOAuthProvider>
	);
}
